version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - C:\Users\dell\library_management_system\Database\data:/var/lib/postgresql:rw

    ports:
      - 5432:5432
    
    environment:
      - POSTGRES_DB=libraryDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Library@docker123


  adminer:
    image : adminer
    restart : always
    ports :
     - 8080:8080